<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sa</name>
   <tag></tag>
   <elementGuidId>f79798a2-cc9c-44f0-8c4a-845c811ca493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='row_17']/td[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>797f4e40-0f5f-45cb-907e-a824a3b01d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/Category/Edit/17</value>
      <webElementGuid>b7859d0f-5b41-4915-8f16-e92443d8231b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>4fd1f4bc-919b-4ca5-a856-1cac9a554993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sửa </value>
      <webElementGuid>f7197101-36f2-4911-b897-7f4c2f0c7674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_17&quot;)/td[5]/a[@class=&quot;btn btn-info btn-sm&quot;]</value>
      <webElementGuid>b23c11d2-312b-44bd-9eef-05b9f0f6414d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_17']/td[5]/a</value>
      <webElementGuid>6f694486-7f5f-4bdb-8911-899654c86d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sửa')]</value>
      <webElementGuid>de2dde78-6622-42d9-a340-f2cd5148cf1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/Category/Edit/17')]</value>
      <webElementGuid>7977ea09-d7e5-44af-85b0-984d69197ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>b4a7cd1d-bbaa-4f1d-aa51-37a12da72f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/Category/Edit/17' and (text() = ' Sửa ' or . = ' Sửa ')]</value>
      <webElementGuid>b073e7b9-980c-4bd1-8686-6b3a6223b014</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
