<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TenTheloai</name>
   <tag></tag>
   <elementGuidId>e9dc2eda-8556-4dae-982b-244a4c1335e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TenTheloai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TenTheloai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab9e7b37-aeb1-4020-a4d0-a04ed90d40f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>88835ac2-efcd-448d-8557-78e7697d63b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba61405c-05e5-4b52-b6fb-83f3030cdcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Tên thể loại must be a string with a maximum length of 250.</value>
      <webElementGuid>e775e39f-fb63-4215-8e4c-3b371a0bb7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>54ac1e4f-fc14-49d4-9438-91f907059a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Tên thể loại field is required.</value>
      <webElementGuid>2477eda4-83f8-479c-882a-5960e449e154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TenTheloai</value>
      <webElementGuid>f3593bd5-4971-4573-b96b-2b651a351cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TenTheloai</value>
      <webElementGuid>220feebd-dc8e-4630-a649-84041f60822d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32df631f-c53b-4c89-8d70-a789fbb83464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kinh tế</value>
      <webElementGuid>5e592f83-ebd0-4f41-8641-6ef114d41eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TenTheloai&quot;)</value>
      <webElementGuid>a8761ada-8cba-46f6-8ff1-bc41d79a4a93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TenTheloai']</value>
      <webElementGuid>1254d028-1b2e-4004-b67b-9c1ca3b3d0ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>94715a92-e61e-4d79-ab2a-e7bcaa018fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/input</value>
      <webElementGuid>aa94d863-a7f6-4369-8d7f-98f466d9110b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TenTheloai' and @name = 'TenTheloai' and @type = 'text']</value>
      <webElementGuid>26570e67-e59c-425a-ac0f-f283956c5118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
