<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xa</name>
   <tag></tag>
   <elementGuidId>54fafef7-383b-4bc5-9b89-1252b051f380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.btn-sm.far.fa-trash-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='row_17']/td[5]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1ceaf305-a7bc-455d-a668-363f4d49177a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm far fa-trash-alt</value>
      <webElementGuid>881c818b-e643-496d-8423-08decaadf47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0632265-165e-4d7b-91ba-a0aadf276d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>$('#row_17').remove()</value>
      <webElementGuid>8bfd4152-2a2b-45da-8cb9-3ae396c3a052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-confirm</name>
      <type>Main</type>
      <value>Bạn có muốn xóa thể loại này?</value>
      <webElementGuid>c16fa5c4-0773-4e8a-9ca5-8c7badcddfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>9cf20e3d-6af8-4a37-80db-8acade614264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/Category/Delete/17</value>
      <webElementGuid>3df3ba25-617c-4992-b44c-3c9b6727209c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Xóa</value>
      <webElementGuid>b16b2d67-e192-4482-aeab-1147af54dfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_17&quot;)/td[5]/a[@class=&quot;btn btn-danger btn-sm far fa-trash-alt&quot;]</value>
      <webElementGuid>004be9be-0108-4841-9fb9-a4e1387ebdf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_17']/td[5]/a[2]</value>
      <webElementGuid>9d223cb2-55b3-4b20-8b85-872c798ed1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xóa')]</value>
      <webElementGuid>e1aed388-3a22-4696-9bef-b4728153bc67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/Category/Delete/17')]</value>
      <webElementGuid>04f9c9b3-2d12-4506-a674-9dd6b99b5049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a[2]</value>
      <webElementGuid>431e6748-0d3b-4e2f-9327-e4068ac5d919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/Category/Delete/17' and (text() = ' Xóa' or . = ' Xóa')]</value>
      <webElementGuid>0314006a-f8e6-4b85-926c-8e6203586403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
