<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_To n nhp (1)</name>
   <tag></tag>
   <elementGuidId>6dfa9009-c5ce-4589-96dd-356bb1213a81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='row_66']/td[6]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b91c1102-7156-4b48-8bc0-04b30c699763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/NhapHang/LapPhieuNhap/66</value>
      <webElementGuid>2cc438c8-ea5b-43b8-b84c-fe964a8fbb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>e8c404f6-2a01-4e9a-ac29-7ffe70aa678f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tạo đơn nhập. </value>
      <webElementGuid>34816249-1450-4eb1-84e7-2325f6c96f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_66&quot;)/td[6]/a[@class=&quot;btn btn-info btn-sm&quot;]</value>
      <webElementGuid>d13f23f7-e519-4268-879e-53bf5a6d39d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_66']/td[6]/a</value>
      <webElementGuid>6481043a-7803-49ce-9fab-7a1ddd559c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tạo đơn nhập.')]</value>
      <webElementGuid>4a5ce71f-e6d7-49cd-adc3-bad6a4dd3d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/NhapHang/LapPhieuNhap/66')]</value>
      <webElementGuid>357f0afb-a811-4130-bef2-971d2af18bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>8559f432-ff26-4cc1-99e2-a4a87b3e53e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/NhapHang/LapPhieuNhap/66' and (text() = ' Tạo đơn nhập. ' or . = ' Tạo đơn nhập. ')]</value>
      <webElementGuid>8dbb746c-75e3-42cb-94d5-3d9cf3f77b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
