<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passWord</name>
   <tag></tag>
   <elementGuidId>d338c245-fa07-4af8-921b-cfe3b8f51ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputmk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputmk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35a02917-c300-4624-a6fe-17360b5c6c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>1a614a2c-e0c4-45cf-9427-71954593e42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2da3bbd6-3aa3-451a-ba76-4cb184f5adf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5ff0054-25b9-4744-a805-457775e3da43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Mời nhập mật khẩu</value>
      <webElementGuid>a42f5775-3fea-4212-91b0-9a24942316d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputmk</value>
      <webElementGuid>f076c73b-82c8-418e-8e6f-9688859e8bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passWord</value>
      <webElementGuid>93ddd800-ba36-4fc5-82e4-9ceeaf1c32e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật Khẩu</value>
      <webElementGuid>e800c91c-c99c-4d3a-985c-149be25ba90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ca6bfb9d-f8f6-4860-9b96-f60d0ae7d0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputmk&quot;)</value>
      <webElementGuid>811200e4-091e-4fbf-818c-fc4c43f522d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputmk']</value>
      <webElementGuid>3d6eefa8-b312-4c38-8191-8ed249756b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>3c7d4522-5b70-4e9c-8af8-bd50fca9fe99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputmk' and @name = 'passWord' and @placeholder = 'Mật Khẩu' and @type = 'password']</value>
      <webElementGuid>a0cb9c9b-c4a5-4cb5-928f-723021c883e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
