<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search</name>
   <tag></tag>
   <elementGuidId>b26f207f-dae2-4de8-a1b8-a8a92877b569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtKeyWord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtKeyWord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d00fd633-c3e1-4143-9de0-e6efe4afa5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c87a72bb-fbe8-4740-a73f-a47a204dc554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control height-5 rounded-0 border-right-0 px-3 ui-autocomplete-input</value>
      <webElementGuid>b79d4dc2-2333-46b2-a14b-b39599b70a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập cuốn sách bạn yêu thích...</value>
      <webElementGuid>99596fd4-9898-4ea7-837c-c22e31e48b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keyWord</value>
      <webElementGuid>7d5e6cb3-7c7f-4af5-bd3c-331ebe1272cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtKeyWord</value>
      <webElementGuid>39adecfb-0f13-4009-9629-c2835fbef905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Amount (to the nearest dollar)</value>
      <webElementGuid>1d389204-220e-425a-a4ff-9c2c23ba9049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>741f6579-7b0b-4fe2-a208-9c9262a1aa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtKeyWord&quot;)</value>
      <webElementGuid>9fa5692d-c7fe-48e3-9b43-f66e7e691342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtKeyWord']</value>
      <webElementGuid>af9e25cc-0890-4ce0-b39c-0256edd74a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='site-header']/div/div/div/div/div[2]/form/div/input</value>
      <webElementGuid>07090511-1d40-4230-a007-a9af9f97edc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4d753dfa-2c6b-4176-980a-e3558d6c4494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nhập cuốn sách bạn yêu thích...' and @name = 'keyWord' and @id = 'txtKeyWord']</value>
      <webElementGuid>0af42010-a23a-4d89-804a-43fec57b4b0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
