<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NguoiTao</name>
   <tag></tag>
   <elementGuidId>3227fa04-a481-4521-bc34-eded515c4c01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NguoiTao</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NguoiTao']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb806d37-f4e2-40d6-aeab-669e2d54c85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>667a3fae-1b43-41af-8faf-797d68240610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ca2d899b-2835-4a4e-8fa8-b0c5164168d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field NguoiTao must be a string with a maximum length of 250.</value>
      <webElementGuid>8b0bb6ab-bb47-4a9c-807f-c61758146699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>92e9bb7d-ec60-462b-95e3-eeaeca447f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NguoiTao</value>
      <webElementGuid>92b78ee4-fc75-4042-8949-2a2a9ed52f13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NguoiTao</value>
      <webElementGuid>d6f687f1-96a7-4e56-8eea-6563e41a2d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5220eec9-9cbf-444c-8c6a-0fb9718a8b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NguoiTao&quot;)</value>
      <webElementGuid>0a118688-ed80-45d5-8b42-5299834ec355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NguoiTao']</value>
      <webElementGuid>50f52706-bef9-480f-b0a0-6df7accd0df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>ae49766f-76e0-4b4f-b50d-ec1513d15b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>8ee3a271-75b8-43ec-a9e1-a96a2974af17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NguoiTao' and @name = 'NguoiTao' and @type = 'text']</value>
      <webElementGuid>47f52d1d-3966-4266-b4a9-e8b104b0054a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
