<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TenTheloai</name>
   <tag></tag>
   <elementGuidId>6edb3f2b-ed10-44cf-9625-53f2071dc1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TenTheloai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TenTheloai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>002fdd52-ceb4-4162-93ec-bb5fe17f0da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>ddb6cb2c-9d8c-44ad-b771-20c5c1f7c345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f153c18a-3cf6-46d2-96d8-97befd5a2671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Tên thể loại must be a string with a maximum length of 250.</value>
      <webElementGuid>5789967e-0b19-48e7-b379-d41b5c21dcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>842c98d2-f8e4-4834-a690-42ff5a7a1d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Tên thể loại field is required.</value>
      <webElementGuid>ad42cd69-75ab-45eb-9111-01a4c775ae49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TenTheloai</value>
      <webElementGuid>445ead16-a469-4fee-b831-46385d4a4af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TenTheloai</value>
      <webElementGuid>4f59e4a1-48ae-438e-bf46-43fea97bdc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0db22a27-2219-41b7-bf00-d503e8c67f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TenTheloai&quot;)</value>
      <webElementGuid>9f7ce7de-255f-4296-88f0-079b9f040559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TenTheloai']</value>
      <webElementGuid>76ba90d6-6523-404d-b9d3-12970d681a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>a9e05c50-1511-40f8-af12-715c94c60d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/input</value>
      <webElementGuid>15c2e5ef-a390-48ea-b3bb-ac250ffd517a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TenTheloai' and @name = 'TenTheloai' and @type = 'text']</value>
      <webElementGuid>8f37033c-5d83-4740-a955-4999cde7d234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
