<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xa</name>
   <tag></tag>
   <elementGuidId>38a5f0e5-0160-484e-9b36-aabdb99cad10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.btn-sm.far.fa-trash-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='row_64']/td[8]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>435aedc5-80d9-4f24-b374-21ee6ac2945c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm far fa-trash-alt</value>
      <webElementGuid>a63fd070-4af0-45fa-8b86-97a3d2b3d1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c51b826a-7426-470e-8054-50616cb484d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>$('#row_64').remove()</value>
      <webElementGuid>ebc5f7b6-b9ca-43f3-a16a-a3b66cae9c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-confirm</name>
      <type>Main</type>
      <value>Bạn có muốn xóa sách này  ?</value>
      <webElementGuid>00e31edc-772b-47c8-b801-e3ceeb3b5f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>0ef47599-0112-47cf-a8c9-8ba6e66333b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/SanPham/Delete/64</value>
      <webElementGuid>618d0c2a-f604-4947-8ba6-73b0873adfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Xóa</value>
      <webElementGuid>98446fd2-dbe4-4d05-8ff4-67ad4175de72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_64&quot;)/td[8]/a[@class=&quot;btn btn-danger btn-sm far fa-trash-alt&quot;]</value>
      <webElementGuid>83b6fed7-b0e7-40e5-a635-20189533d8ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_64']/td[8]/a[2]</value>
      <webElementGuid>6a05c570-69ab-4689-9b8e-460068ec36a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xóa')]</value>
      <webElementGuid>87436ad3-8e0b-4e8c-ba25-6acf69ea8137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/SanPham/Delete/64')]</value>
      <webElementGuid>206cc2fa-9ab9-4d4d-8920-79de476100b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a[2]</value>
      <webElementGuid>3efe2f1d-735c-4939-b144-8f10be06c469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/SanPham/Delete/64' and (text() = ' Xóa' or . = ' Xóa')]</value>
      <webElementGuid>75a91e69-cf62-4ed6-b138-b431e9b233f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
