<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Xa_1</name>
   <tag></tag>
   <elementGuidId>ce544074-8487-49ab-bc7a-d42988c7ffa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger.btn-sm.far.fa-trash-alt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='row_63']/td[8]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5adc20db-8a8f-4481-8a03-dd6cec10b7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-sm far fa-trash-alt</value>
      <webElementGuid>48b5c05a-1d5c-4582-8890-d91c96887ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e3425ea-254a-469f-b585-01f399b114e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-complete</name>
      <type>Main</type>
      <value>$('#row_63').remove()</value>
      <webElementGuid>9c45cd43-6520-4814-b91b-36685ab5183c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-confirm</name>
      <type>Main</type>
      <value>Bạn có muốn xóa sách này  ?</value>
      <webElementGuid>da02a494-dbd5-419f-bc37-af76364751d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ajax-method</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>5e14d68a-aa82-4b22-b09e-21116d573179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/SanPham/Delete/63</value>
      <webElementGuid>ba538b36-0ca6-4145-8511-3bd0941d5b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Xóa</value>
      <webElementGuid>41dfb967-c090-4863-ba0b-764dcb8038c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_63&quot;)/td[8]/a[@class=&quot;btn btn-danger btn-sm far fa-trash-alt&quot;]</value>
      <webElementGuid>2c484e05-5888-4888-ac51-2a56b1d5b455</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_63']/td[8]/a[2]</value>
      <webElementGuid>4eb55719-cd31-4279-adc1-98041c283e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Xóa')]</value>
      <webElementGuid>c28729d5-dc3e-4c05-ae3a-70a13cb4231f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/SanPham/Delete/63')]</value>
      <webElementGuid>2295cb02-32a2-420e-9625-ee4d18486125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a[2]</value>
      <webElementGuid>d1638e19-72f3-401e-9d9d-bae1a4ab10e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/SanPham/Delete/63' and (text() = ' Xóa' or . = ' Xóa')]</value>
      <webElementGuid>bd4d3976-d290-4d76-9add-8fe65450782c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
