<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chn nh</name>
   <tag></tag>
   <elementGuidId>aa7cfad8-d230-45cd-a1a0-10a36484dfa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSelectImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnSelectImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>389b2876-2982-4bc8-a8b8-2d0010a3c825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSelectImage</value>
      <webElementGuid>c8d6860b-c911-44cb-a2ac-c9dca7b43046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4fc9ea93-cd82-4726-8048-4f8b8436b912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn ảnh</value>
      <webElementGuid>f1c3650b-2086-4ae4-9ea0-459adf1a0dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSelectImage&quot;)</value>
      <webElementGuid>f412fd6d-93e8-40dc-9c06-15f1da3d60a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnSelectImage']</value>
      <webElementGuid>df6a6cbf-22fc-4285-a5a4-76fe567c1089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div[4]/div/a</value>
      <webElementGuid>3f6a83e0-50c8-4ca2-bc08-f84cab61dc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Chọn ảnh')]</value>
      <webElementGuid>9abacd2a-ede0-4053-a65e-cb15ad231748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>57ee5ad2-3186-479d-a6ca-1c41101c2660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>6e6bd785-bf31-45a6-98e3-8334de2481fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnSelectImage' and @href = '#' and (text() = 'Chọn ảnh' or . = 'Chọn ảnh')]</value>
      <webElementGuid>1bb04223-c9c3-46af-977a-e8d0ef50afe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
