<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sa</name>
   <tag></tag>
   <elementGuidId>30af9605-cce5-492d-97c5-9b4bb10616bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-info.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='row_65']/td[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f91277d0-116c-4ce5-b4ae-0b05e41ad3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/Sanpham/Edit/65</value>
      <webElementGuid>af44a2c9-0dfb-40dd-bb24-73eb11f8234d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info btn-sm</value>
      <webElementGuid>56e0513a-33fe-41af-a531-04c8ed859a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sửa </value>
      <webElementGuid>f704368a-4a0e-46be-9c74-89161b0188c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;row_65&quot;)/td[8]/a[@class=&quot;btn btn-info btn-sm&quot;]</value>
      <webElementGuid>cdfd76e8-f2b9-4eaa-89bf-c99b77753201</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='row_65']/td[8]/a</value>
      <webElementGuid>8b322f8a-45cf-4f73-a1d6-75eeb4200c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sửa')]</value>
      <webElementGuid>faf82b46-d164-4c6e-bfde-c9e2250363a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/Sanpham/Edit/65')]</value>
      <webElementGuid>7215ab74-319f-4cfc-9c41-3248712741d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>ab772233-ea90-4f9a-9be1-99168e7c930a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/Sanpham/Edit/65' and (text() = ' Sửa ' or . = ' Sửa ')]</value>
      <webElementGuid>b90653ca-e6c2-4833-9298-669f47fa3f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
