<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TacGia</name>
   <tag></tag>
   <elementGuidId>5e0f077a-97fa-43e4-b0bf-bf43727da405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TacGia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TacGia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4af7d5b-1216-4bda-915d-c58cd7210437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>163a8586-2cd0-4b5b-9ac7-432b92eb1b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1db44c8-dfd2-49c1-97d4-958735c1b3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Tác giả must be a string with a maximum length of 50.</value>
      <webElementGuid>30064ba2-3d59-47f6-bd9f-d648ca7c2ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1be6b75c-72a6-4e22-93c8-0e3d4f413da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Tác giả field is required.</value>
      <webElementGuid>70b9f80f-ca5a-49c0-85e5-3c73eb007398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TacGia</value>
      <webElementGuid>04a0ba0f-6cbf-4a7f-a545-f77e1340966b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TacGia</value>
      <webElementGuid>e3fe939c-32de-4f6c-85e6-a7b756bcc9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>960b3298-0ce3-44dd-9989-a48dbe580496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tỗ Hữu</value>
      <webElementGuid>cd39ed0f-9bd1-4bc4-879c-35b9f14f491e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TacGia&quot;)</value>
      <webElementGuid>dce314a1-90f9-4fb5-adf9-4a7a84798a07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TacGia']</value>
      <webElementGuid>bcd6d0eb-82de-4b5e-948d-6f4f1e7d1b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>b110be1e-e6e6-4a83-898c-470689d13833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>669d5700-2115-4eb6-87fd-dc045a622658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TacGia' and @name = 'TacGia' and @type = 'text']</value>
      <webElementGuid>757d5d3a-1175-43a2-b5be-f6707a3e743e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
