<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GiaNhap</name>
   <tag></tag>
   <elementGuidId>05c7c293-ccfb-4684-bc11-856a5054824f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GiaNhap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GiaNhap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e603f3b4-79b3-49e9-a22e-7523c6e589ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>a781cbea-9846-4384-88c7-9a9fbb6920a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d04279a-245a-4f9f-b2eb-e1043f298e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Giá Nhập must be a number.</value>
      <webElementGuid>e2913694-72be-4ee8-bf40-e2894eecfbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GiaNhap</value>
      <webElementGuid>9bd41432-f0be-4dcb-a26e-62d8189166fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GiaNhap</value>
      <webElementGuid>87d07598-d80b-42f0-9e1f-395018b696ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>021db3e8-1ba8-4c32-ab1d-8d1527518090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>15000</value>
      <webElementGuid>10fdd024-87f4-478f-a345-ebaeac7e4b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GiaNhap&quot;)</value>
      <webElementGuid>5b73cf38-9187-429f-b8c1-b8fbcaf3ff46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GiaNhap']</value>
      <webElementGuid>b3946b80-f60d-4442-a011-2d2c399bf6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>753c14db-a7f4-4a46-b71c-2497b738d251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>2f88361c-edbe-4aea-99a5-8266e3a2ff65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GiaNhap' and @name = 'GiaNhap' and @type = 'number']</value>
      <webElementGuid>faef6cbf-7e27-4b97-b76c-a6ce9ddf62b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
