<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NhaXuatBan</name>
   <tag></tag>
   <elementGuidId>808577d6-9ee7-4ad6-be11-da75e8ae92c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NhaXuatBan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NhaXuatBan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e71dd2e4-97b7-4162-aaa2-e961e61e43b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>448c2a0a-6f12-4578-a700-40a1f2cf53fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3548b7b6-7da1-4925-aee9-4d3be1a1a6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Nhà xuất bản must be a string with a maximum length of 50.</value>
      <webElementGuid>2a9e8cb4-d4c3-42dc-b133-45a20b82a343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>33873957-97ff-48cf-aa68-24698fffad1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Nhà xuất bản field is required.</value>
      <webElementGuid>d7bcabcd-10de-4c34-aa98-e183cbecae7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NhaXuatBan</value>
      <webElementGuid>c1d29f44-284c-4f4a-bf45-b221a9eaf09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NhaXuatBan</value>
      <webElementGuid>15647d00-afad-47dc-adce-719e56da8bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cdcf5c1-27ab-4bab-a072-678ee0860cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Kim Đông</value>
      <webElementGuid>b1199396-ad48-46ac-a173-1f709c12e755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NhaXuatBan&quot;)</value>
      <webElementGuid>0e366f60-5cb8-437e-95e5-a6eafe04e5c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NhaXuatBan']</value>
      <webElementGuid>15ee03a0-10ff-45a7-b063-76a682797353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>ee3d0614-3cb4-46ad-acb6-ff9b7601826d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b4c2663a-cd3b-4b4f-b860-98a550ee32d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NhaXuatBan' and @name = 'NhaXuatBan' and @type = 'text']</value>
      <webElementGuid>a2576f76-abf5-4388-9ece-048a2201e238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
