<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GiaTien</name>
   <tag></tag>
   <elementGuidId>479996ce-1023-4c51-b5fd-64e1633c463a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GiaTien</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GiaTien']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7934144c-7f36-4e35-993e-e0bdcba862a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>102de523-523d-420b-90e7-f724e305fda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80c20718-f49c-456f-85f4-e8e50bb01f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Giá Tiền must be a number.</value>
      <webElementGuid>2bc93b8d-d68a-4c2a-b64a-0c1c7a36f602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Giá Tiền field is required.</value>
      <webElementGuid>a6b75ea8-be8d-4140-b08f-49060d6344dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GiaTien</value>
      <webElementGuid>3167caee-9cab-49a9-a4eb-eab1f2077c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GiaTien</value>
      <webElementGuid>2687f4b7-d2d7-4a06-9e99-a363b8d68799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>163af345-b1be-4a92-b876-71e2579e53bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>19000</value>
      <webElementGuid>84965aed-f1e1-4fbd-8bdb-6ecbfd4ccdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GiaTien&quot;)</value>
      <webElementGuid>0e81f141-6696-4c32-b312-7ac350d885f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GiaTien']</value>
      <webElementGuid>751e57f2-d8f2-47e6-a0b6-63e3245902f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>83f86c6e-3f2e-46d5-b0e8-47b567e5e7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>36c871ad-c5f9-429e-9201-7150b9b4ef4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GiaTien' and @name = 'GiaTien' and @type = 'number']</value>
      <webElementGuid>736212e2-2ef6-4af6-af75-5cca1f0c6e3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
