<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status</name>
   <tag></tag>
   <elementGuidId>144289b3-b118-4aeb-b504-82f756301702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6bace07-3772-4643-a90d-68554c46d7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>e01e558c-e3d7-450a-a8af-1383b9d17e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1aae6265-12a8-4310-8662-fea4dd82ae9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fca2d412-c062-413a-aa29-2ddba883833b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Trạng thái field is required.</value>
      <webElementGuid>8110e902-d19d-4967-8a96-4d84b61284de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>2f9734b6-3ec0-4f00-bc0c-cdd8a7f968f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>2b73f2a7-751b-494e-988a-2e0f980dabe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f06551a1-b655-402e-b999-75abf705b0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c36b1978-9fb8-46f6-a012-73e36d724d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Status&quot;)</value>
      <webElementGuid>5a93531b-0f9b-470d-8b92-f0e8a970352a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Status']</value>
      <webElementGuid>25cb43e7-a564-4fcc-ac76-1c6c0e3bda22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div[6]/div/input</value>
      <webElementGuid>11306920-58e6-4018-b09a-478a1232a886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>f34849d7-3c76-436c-a2fe-836e58216cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = 'Status' and @name = 'Status' and @type = 'checkbox']</value>
      <webElementGuid>0af134cd-f08e-4939-80c0-ef7517bc0247</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
