<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sch hay</name>
   <tag></tag>
   <elementGuidId>74788929-1d72-41b8-a8e5-2ad83d9fbb65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Mota</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Mota']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d62f6b56-f855-43ab-afea-dda4c93abd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7fb704d5-4ae7-474d-b0f0-2355808d14cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>18d47186-8cc9-4372-b223-595d7767908b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Mota</value>
      <webElementGuid>ffb58896-1b8b-4ad7-ba81-1bae0966ee4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mota</value>
      <webElementGuid>4f6482ef-bf4f-4a3e-afaa-42d17f169fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>00942feb-a39d-4cba-89b6-d4539f1db5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sách hay</value>
      <webElementGuid>61cdd440-5e10-464e-857f-5fa7e491c246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Mota&quot;)</value>
      <webElementGuid>35747fb2-e062-4316-8793-0b3b31c4123c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Mota']</value>
      <webElementGuid>2d321c03-57bc-4740-a3b5-ea0d4629ad05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[7]/textarea</value>
      <webElementGuid>fbd17283-4ca6-441d-9bb3-68570df50ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/textarea</value>
      <webElementGuid>2060361b-10fd-45c6-ad93-b8f06416738b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Mota' and @name = 'Mota' and (text() = 'Sách hay' or . = 'Sách hay')]</value>
      <webElementGuid>f600c92c-d101-4e1b-93b7-be848436d037</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
