<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>c75dabf5-aca7-46e6-b7bc-5307b67785de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.image > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='r0']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f3b61d3-bc59-4b9b-acfb-29bd398a2e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4922b74f-8a12-48a5-9698-e64834d5e2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r0&quot;)/div[@class=&quot;image&quot;]/div[1]</value>
      <webElementGuid>86289e86-8377-4b7e-9e9c-d25d7239ff13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Duy/QL_Sach/Add/Page_CKFinder 2/iframe_CKFinder</value>
      <webElementGuid>c24178b5-6f00-4b82-9e36-b5c9dab253f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='r0']/div/div</value>
      <webElementGuid>86296517-ce81-4380-a372-e3671de0056d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>a71d1c2c-588d-4cf6-ba1b-c0163cdea546</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
