<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1</name>
   <tag></tag>
   <elementGuidId>942d0f7f-edf4-4bff-976a-96c82d57da1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#r8 > div.image > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='r8']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7855d7eb-10d6-4778-9042-94f07a5bbe12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>257489f5-1cdd-4e2f-8656-19c943740a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r8&quot;)/div[@class=&quot;image&quot;]/div[1]</value>
      <webElementGuid>65727871-001e-43dc-8319-92b6d95f33d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Duy/QL_Sach/Edit/Page_CKFinder 2/iframe_CKFinder</value>
      <webElementGuid>27528863-72a0-4fa8-ac78-b7789db8395e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='r8']/div/div</value>
      <webElementGuid>68f7424b-4286-4de0-9723-1e893cca9ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[9]/div/div</value>
      <webElementGuid>9edea332-7e6c-4d34-a880-01ee937aa34c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
