<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Chn nh</name>
   <tag></tag>
   <elementGuidId>ea18d331-d947-4c24-8cbf-7d014247dc6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSelectImage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnSelectImage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b2f4432-ccf2-4b41-86b9-0fd50c332ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSelectImage</value>
      <webElementGuid>b4501eae-9197-45c9-91c5-d42748eea3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>47801120-d78e-40c1-93d6-e420d489a55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn ảnh</value>
      <webElementGuid>383850fd-d8d7-4c2e-ab57-6673b4c8617c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSelectImage&quot;)</value>
      <webElementGuid>3dd81ba8-70de-43fd-ad6a-25f2d9cb1db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnSelectImage']</value>
      <webElementGuid>9056a2aa-f626-4ca0-848c-8bad96fa8e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div[4]/div/a</value>
      <webElementGuid>1eba23ca-9e13-4eab-902d-e13c9fbb538d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Chọn ảnh')]</value>
      <webElementGuid>81375d16-e7de-4d2c-9b8d-6ed3fadcaf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[19]</value>
      <webElementGuid>cfb2d390-a026-434d-a57f-65b634af0aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>a9a9db43-5d07-41e2-b0e4-c955e52b68d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnSelectImage' and @href = '#' and (text() = 'Chọn ảnh' or . = 'Chọn ảnh')]</value>
      <webElementGuid>c2191f9b-d0b6-4eaa-a945-5a80157b2ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
