<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Images</name>
   <tag></tag>
   <elementGuidId>5d69176a-31ce-452a-8b6d-b3902f5cb41a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtImage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtImage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77e533b7-a7f2-4535-b0e5-10de2a5937eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlattributes</name>
      <type>Main</type>
      <value>{ class = form-control, id = txtImage }</value>
      <webElementGuid>72e7ab44-32ea-4794-b8cf-3fbba69591d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtImage</value>
      <webElementGuid>73830227-5500-4467-95bb-48fa3b5d7024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Images</value>
      <webElementGuid>f6d66a04-2a17-4396-b791-f1101eb7e369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02ec9abd-5324-4dba-8bd0-837d082e8ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtImage&quot;)</value>
      <webElementGuid>8e0e696d-d3a6-4230-9f14-81bf2f09625c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtImage']</value>
      <webElementGuid>55713b10-609f-4bbe-9102-77eb583b13f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>715c8315-f70c-484c-8e15-1744bf254f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>6863e655-78fe-45b7-95de-216e8e5db4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtImage' and @name = 'Images' and @type = 'text']</value>
      <webElementGuid>7a657ea0-8884-4f8e-be21-66de3c627f54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
