<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GiaTien</name>
   <tag></tag>
   <elementGuidId>4654cd26-68dd-434c-a7ce-a2166e7f2003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GiaTien</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GiaTien']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52c06b14-bfb3-40cf-917f-87af4b9e701f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>f601e150-11e4-4470-b6c5-db1f1708d6c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8da90f55-9b55-485a-afff-7bdb5a9f778d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Giá Tiền must be a number.</value>
      <webElementGuid>0db71677-8ade-469a-8dd4-e061c57cfc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Giá Tiền field is required.</value>
      <webElementGuid>465f9f03-83f3-4714-8f73-1c2b306f0508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GiaTien</value>
      <webElementGuid>d22dd897-4ad0-4e03-b0df-0b4514b0bdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GiaTien</value>
      <webElementGuid>22073dc9-a9c9-485f-bd5c-315190623e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>59dad2c6-4f89-4394-a924-d2d4dcaf7079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GiaTien&quot;)</value>
      <webElementGuid>96296478-9426-4692-8bd0-780514d099b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GiaTien']</value>
      <webElementGuid>f57fbf1c-3d59-4a84-8177-83293ccc2fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>873fd876-7f7e-4f83-86c5-0791532f60f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>1f9c4463-822d-47df-859d-84918f07b89b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GiaTien' and @name = 'GiaTien' and @type = 'number']</value>
      <webElementGuid>d412ba2d-1b42-493d-8b8d-a796c4c114d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
