<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GiaTien</name>
   <tag></tag>
   <elementGuidId>2f4e1968-f799-4bba-b4bb-bf563685ca74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GiaTien']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GiaTien</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5b53167-6eda-4c36-9cf9-7ae501926095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>e5bb858d-be07-443f-9122-2647fed12df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>66509fe0-6145-46d2-947d-d2a0f7bc78d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Giá Tiền must be a number.</value>
      <webElementGuid>1a8554ac-4d68-49f3-a030-83e4dc2568f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Giá Tiền field is required.</value>
      <webElementGuid>14763193-7459-49ac-b53e-515a258aae4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GiaTien</value>
      <webElementGuid>999da015-0cef-4a82-b78b-914ca5d1f262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GiaTien</value>
      <webElementGuid>f047e389-4632-4f36-ae99-4a688f9f98ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2fb5037f-e94f-4297-97eb-7c4f2477e9a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GiaTien&quot;)</value>
      <webElementGuid>3a305088-b974-469b-af35-a8438228b2f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GiaTien']</value>
      <webElementGuid>e089142a-6273-4773-9754-78421f9b614d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>a8acbfd2-42bb-48f1-8ac5-77eeeee482a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>daacba0d-57d1-4702-8759-156b85e6dc98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GiaTien' and @name = 'GiaTien' and @type = 'number']</value>
      <webElementGuid>de3dc322-79a0-4f13-8c18-15d9d0021129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
