<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NhaXuatBan</name>
   <tag></tag>
   <elementGuidId>5896b7a8-58ed-4dac-866e-524b5dd9525b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NhaXuatBan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NhaXuatBan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f97134b-6b45-4cd7-ba48-e3a2ff3d28c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>722e808b-1d37-482a-af23-49c63c376380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>11acf1ec-47f2-4ca6-8d35-2e5b1aa39ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Nhà xuất bản must be a string with a maximum length of 50.</value>
      <webElementGuid>b28d157c-c6fb-4838-867b-919f44f8ddfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>8b9ab506-8047-484f-8187-977cae53163e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Nhà xuất bản field is required.</value>
      <webElementGuid>b12c2038-082c-4161-8e27-c23bc2251d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NhaXuatBan</value>
      <webElementGuid>4cc15ba6-682d-45eb-a562-c9144a860fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NhaXuatBan</value>
      <webElementGuid>ed1592ba-61db-4741-9b4f-a897249a2656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bd9e616-997b-4b20-8f01-cd30c8828447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NhaXuatBan&quot;)</value>
      <webElementGuid>ab411220-ea23-4f8a-ad0b-50f57d52d30d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NhaXuatBan']</value>
      <webElementGuid>f7f9a305-017f-4529-9e35-43cd7544d1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>3654f0c8-673d-46ce-a158-f596d8336057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>fbf5238a-afdd-4203-bbac-9d08dd769f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NhaXuatBan' and @name = 'NhaXuatBan' and @type = 'text']</value>
      <webElementGuid>b5174e34-a669-470f-ad9d-6b6c618f1c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
