<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TacGia</name>
   <tag></tag>
   <elementGuidId>c80b4d73-49c8-481b-bdd2-8e450d61307d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TacGia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TacGia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64c21de0-83a0-4f22-b08e-7a159c1fad52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>19dc97b1-2c86-403d-9680-4418ea510c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d8a56a1e-5a62-45b1-b2de-bcebdafeb9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Tác giả must be a string with a maximum length of 50.</value>
      <webElementGuid>3bbabb15-444e-44a1-880d-327f89403920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b756a081-a8a9-4606-9b58-8fce721a4d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Tác giả field is required.</value>
      <webElementGuid>5363367f-2dcc-4520-96c5-3f4ef06b3fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TacGia</value>
      <webElementGuid>1c723ad7-33b5-4359-90ca-0291e014efae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TacGia</value>
      <webElementGuid>a811d50d-a2cd-4cf6-9b85-99ba109ef593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ae8a569-0544-4862-86b8-bc40517141b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TacGia&quot;)</value>
      <webElementGuid>c3a8d858-8a61-4045-b9c5-25e48bc308b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TacGia']</value>
      <webElementGuid>d7aa1983-8e8c-4fae-9dc3-ef893a54359c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[3]/div/input</value>
      <webElementGuid>ab185be7-4cfe-4926-86a9-ab395d0d00fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>09b9134e-6ac6-4c9f-ab97-0b6e0924b91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TacGia' and @name = 'TacGia' and @type = 'text']</value>
      <webElementGuid>38c18014-80e9-4624-981c-03d61a575d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
