<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PriceSale</name>
   <tag></tag>
   <elementGuidId>b704d3f3-b657-40d7-b8d7-6e30f6e063e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PriceSale</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PriceSale']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfe12afb-efcb-4c41-ae2e-13818d95facd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>b2463869-0caa-4bf1-af6f-15fe05fe1222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c90c4d37-8bf1-48a1-a8c5-f2c5fc8e38f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Giá Khuyến Mại must be a number.</value>
      <webElementGuid>10297b8a-9c0d-4161-b578-292c675e2cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PriceSale</value>
      <webElementGuid>ff281b2c-1ca4-4cf9-9e6f-c767b072296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PriceSale</value>
      <webElementGuid>97a515a8-2844-4a7d-a9d7-7f278e12fc73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b0ad1cfa-2233-4731-b941-e1ac072db28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PriceSale&quot;)</value>
      <webElementGuid>f98ae96e-5eb4-4943-8387-5e1ced038bf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PriceSale']</value>
      <webElementGuid>d9e672ac-993b-4630-9977-e4d1c739ccc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div[3]/div/input</value>
      <webElementGuid>e907c885-e2d6-410b-9099-c65485be34f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>35fb0f86-627f-4ab2-8245-704368219d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PriceSale' and @name = 'PriceSale' and @type = 'number']</value>
      <webElementGuid>7b5695a5-570f-4802-9d5b-bee95d0babdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
