<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GiaNhap</name>
   <tag></tag>
   <elementGuidId>bc23ff9d-ce2f-4e49-b06f-ff910e7707fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#GiaNhap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='GiaNhap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42e865e6-a3e6-4288-b2c6-d66f3772fa3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>07a58eb3-45e2-4be9-acfd-96982605273a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b913405e-ce27-4579-9c3b-a2075f77c22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-number</name>
      <type>Main</type>
      <value>The field Giá Nhập must be a number.</value>
      <webElementGuid>1fa1c802-2dff-4152-b29f-26eb5950e115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GiaNhap</value>
      <webElementGuid>77a253b8-8577-4625-9a70-834ea0a989ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GiaNhap</value>
      <webElementGuid>17b55fe8-2ef2-4ab3-aed6-f679dbcb405c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>79bbfffa-54a1-4057-b87f-3d85064f473b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GiaNhap&quot;)</value>
      <webElementGuid>41b85a7a-39ac-4209-8f05-8b974b5c3362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='GiaNhap']</value>
      <webElementGuid>58dd9295-6b20-4e4a-9257-550d12583ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>6e11f875-a620-48fc-b23c-5010314ad15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>e713fadd-ad92-45bd-9198-79503ddef615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'GiaNhap' and @name = 'GiaNhap' and @type = 'number']</value>
      <webElementGuid>5f318200-35ef-44b8-9dab-4c2de365ce93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
