<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NhaXuatBan</name>
   <tag></tag>
   <elementGuidId>cfbeedf1-9655-4323-a3c0-ed9ff8bc6503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NhaXuatBan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NhaXuatBan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>288d4ec4-8a83-4840-ab14-ddaac20ceb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>1393ad9f-cbae-41a9-b71f-9f099e64c029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ba1727a9-4921-46bd-acc2-93c862c8bfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Nhà xuất bản must be a string with a maximum length of 50.</value>
      <webElementGuid>4930313d-e5f4-4e27-8cff-73a06fddb0fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f97dfc7c-418f-4270-8b3d-5d7a37f1e5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Nhà xuất bản field is required.</value>
      <webElementGuid>781be15f-b6e5-46eb-bea5-6d7554d3b348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NhaXuatBan</value>
      <webElementGuid>ac8a8811-9538-4025-af3d-0529e114ea31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NhaXuatBan</value>
      <webElementGuid>a61d9e06-008c-48a6-ad18-6891b1ec3750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83eff56f-18ba-4c63-8bb1-cf358695051b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NhaXuatBan&quot;)</value>
      <webElementGuid>99891577-8032-45ad-b842-cb05ff34cc97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NhaXuatBan']</value>
      <webElementGuid>14417708-e391-404f-9735-873492f3ce37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[4]/div/input</value>
      <webElementGuid>7eed534f-12cb-4291-990e-237045bc2b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>0aba362a-75d2-406b-82bc-f3953d9fb4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NhaXuatBan' and @name = 'NhaXuatBan' and @type = 'text']</value>
      <webElementGuid>0e4aaf99-ef51-4b6b-832b-986b3bf4d683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
