<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Mota</name>
   <tag></tag>
   <elementGuidId>652421e4-1d66-4bc1-906e-40d40ff15aa6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Mota</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Mota']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f2398d84-9399-41ad-90c1-dd527ff46fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6a7ecafc-b71d-4e82-95f5-0bdddee43388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>dc62679a-249b-4d92-8de3-8b90e51f3eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Mota</value>
      <webElementGuid>8f4a2377-b7e7-4e84-a564-6f2fa0921bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Mota</value>
      <webElementGuid>2c7f697e-8157-4c23-85e3-3f6a54ec6b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e83fc942-7bde-4935-a1ce-4a1a94c08476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Mota&quot;)</value>
      <webElementGuid>51d42b8f-fa95-4f70-b157-0a7d802d4bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Mota']</value>
      <webElementGuid>e873c614-a7b5-4500-a3e9-fc9750ab1426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/div/form/div/div/div/div/div/div/div[7]/textarea</value>
      <webElementGuid>fc38b767-367c-4066-8b3d-bbe8b4a8ba1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/textarea</value>
      <webElementGuid>214b0c9b-2fb9-47c3-9ce1-09ebe4fe15e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Mota' and @name = 'Mota']</value>
      <webElementGuid>8281a7c7-ee4b-46b4-865e-42957e412540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
