<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passWord</name>
   <tag></tag>
   <elementGuidId>00a0eb10-353b-447e-9450-f98837f8b29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputmk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputmk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8ba770e-6958-4418-856e-27d49219b5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>3dd6c42a-0b02-46e3-b08d-cce1b0e3ee9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7ea5b096-a63e-4489-90c4-423818fb1ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>250b9219-9885-4021-b3c3-303da2b1a13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Mời nhập mật khẩu</value>
      <webElementGuid>92b0cb46-5d17-44e2-bc2c-e848c258553d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputmk</value>
      <webElementGuid>134f5e84-b4cb-44c8-9222-879ba9965c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passWord</value>
      <webElementGuid>55c529b8-bd66-4ea8-ba2b-377f019edb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật Khẩu</value>
      <webElementGuid>aebb4c86-796b-4795-a96f-ce49d4d8c0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3dd6b2d9-f001-4852-ac12-d0dcc881bb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputmk&quot;)</value>
      <webElementGuid>efe4f73c-c7f3-45aa-9d7a-f49c4d74547b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputmk']</value>
      <webElementGuid>14af381c-036a-457a-be7d-a95d9a5c036f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>ede24240-a190-4d91-a4ea-651a197242a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputmk' and @name = 'passWord' and @placeholder = 'Mật Khẩu' and @type = 'password']</value>
      <webElementGuid>83b16798-5053-4c9d-946d-8f38035ef327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
