<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_passWord</name>
   <tag></tag>
   <elementGuidId>3730ffd6-4591-4b47-a031-75c1922bcc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputmk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputmk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>144bab97-3025-4c73-9536-e20b1c8c4d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>fcf3d994-8bc1-486f-8bc7-d36572ea11c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb7c36da-de8f-44db-a147-477bea505ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e7d595c5-3351-4018-b55b-f11f24604ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Mời nhập mật khẩu</value>
      <webElementGuid>8e1a332d-aef1-420a-9923-5fef92315ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputmk</value>
      <webElementGuid>db9ba08d-b2f0-4469-976e-725ae19c560e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passWord</value>
      <webElementGuid>1a89afa4-d056-4008-a499-183a1f9947a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật Khẩu</value>
      <webElementGuid>ae312ee1-8753-44d8-8879-5b3c312a34e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1e0e4414-76de-479a-a218-2a6425805a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputmk&quot;)</value>
      <webElementGuid>0393e71d-f0ae-4e79-ad43-fe5cf833735b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputmk']</value>
      <webElementGuid>7260fca2-00d0-4db2-916c-2704383f6937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>658d6798-22b7-4807-88ce-4815e662909e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputmk' and @name = 'passWord' and @placeholder = 'Mật Khẩu' and @type = 'password']</value>
      <webElementGuid>b3b593b5-5966-4e78-a421-082f7b88e700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
